luisfelipemacedo/adoptme

Gemfile
Gemfile.lock
app/models/user.rb
app/views/layouts/application.html.erb
config/environments/development.rb
config/initializers/devise.rb
config/locales/devise.en.yml
config/routes.rb
db/migrate/20230828200032_devise_create_users.rb
db/schema.rb
test/models/user_test.rb

I just added the devise using Lewagon´s lecture

devise added

---

Gemfile.lock
app/models/adoption.rb
db/migrate/20230829142041_create_adoptions.rb
db/schema.rb
test/models/adoption_test.rb

Made models & validations for adoptions

adoptions models & validations

---

app/controllers/adoptions_controller.rb
app/controllers/pets_controller.rb
app/models/adoption.rb
app/views/layouts/application.html.erb
app/views/pets/show.html.erb
app/views/shared/_flashes.html.erb
config/routes.rb
db/migrate/20230829172428_change_status_to_boolean_in_adoptions.rb
db/migrate/20230829174902_change_to_owner_in_adoption.rb
db/schema.rb
db/seeds.rb
test/controllers/adoptions_controller_test.rb

Edits to a lot & mainly adoption

Adopt controller

---

app/javascript/controllers/datepicker_controller.js
app/views/devise/registrations/new.html.erb
app/views/layouts/application.html.erb
config/importmap.rb

I created and edited the user´s signup page

Edit users

---

app/controllers/pets_controller.rb
app/views/pages/home.html.erb
app/views/pets/show.html.erb

aaction destroy done

---

.gitignore
Gemfile
Gemfile.lock
app/controllers/pets_controller.rb
app/models/pet.rb
app/views/pets/_form.html.erb
app/views/pets/_pet.html.erb
app/views/pets/show.html.erb
config/environments/development.rb
config/storage.yml
db/migrate/20230829194916_create_active_storage_tables.active_storage.rb
db/schema.rb
db/seeds.rb

terminei de colocar as imagens dos pets. Amanha vou terminar o seed pra 20 novamente

Petsimages

---

app/views/devise/registrations/edit.html.erb
app/views/shared/_navbar.html.erb

editei a parte que o usuario logado pode editar, além de adicionar a action edit na navbar

Edit user fields

---

db/seeds.rb

40 imagens aleatórias de animais usando cloudinary! ficou lindoooo

40 imagens aleatórias de animais usando cloudinary

---

.gitignore
app/controllers/pets_controller.rb
app/views/pets/show.html.erb

Only allowed to edit pet if belongs to seller

Edit Restriction

---

app/views/pets/show.html.erb

Adopt button only pops up when it is not the seller's pet

Adoption edited

---

app/models/pet.rb

image mandatory

---

Gemfile
Gemfile.lock
app/controllers/pets_controller.rb
app/models/pet.rb
app/views/pets/index.html.erb

Filter pets

---

app/models/pet.rb

botao destroy do pet funcionando time!!

butao do destroy funcionando

---

app/assets/stylesheets/components/_btn.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/pages/_footer.scss
app/assets/stylesheets/pages/_home.scss
app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_profile.scss
app/controllers/application_controller.rb
app/models/user.rb
app/views/devise/passwords/edit.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/layouts/application.html.erb
app/views/pets/_pet.html.erb
app/views/pets/index.html.erb
app/views/pets/show.html.erb
app/views/profiles/show.html.erb
app/views/shared/_footer.html.erb
app/views/shared/_navbar.html.erb

Reverts luisfelipemacedo/adoptme#24

Revert "Newhome"

---

app/assets/stylesheets/components/_btn.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/pages/_footer.scss
app/assets/stylesheets/pages/_home.scss
app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_profile.scss
app/controllers/application_controller.rb
app/models/user.rb
app/views/devise/passwords/edit.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/layouts/application.html.erb
app/views/pets/_pet.html.erb
app/views/pets/index.html.erb
app/views/pets/show.html.erb
app/views/profiles/show.html.erb
app/views/shared/_footer.html.erb
app/views/shared/_navbar.html.erb

Reverts luisfelipemacedo/adoptme#25

Revert "Revert "Newhome""

---

app/models/pet.rb
app/views/pets/index.html.erb

If the pet is adopted it will show "Adopted!" in the pet index

More fixes

---

app/views/profiles/show.html.erb

finalizei o botao para voltar a pagina do usuario

Botao usuario

---

app/controllers/pages_controller.rb
app/controllers/pets_controller.rb

pode ver a home / index pets e show pets

adicionei usuario sem estar logado

---

app/controllers/profiles_controller.rb
app/views/shared/_navbar.html.erb

navabar funcionando para logado e nao logado

acabei a navbar para logado e nao logado

---

app/assets/stylesheets/pages/_display.scss
app/assets/stylesheets/pages/_show.scss

Margin in about us and improved the show pets

overall improvments

---

app/models/pet.rb
app/views/pets/_pet.html.erb

Birthday Fixed
